// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMSInteraction.Repository;

#nullable disable

namespace SMSInteraction.Repository.Migrations
{
    [DbContext(typeof(SmsInteractionDbContext))]
    [Migration("20230610114725_InitialWithIdentity")]
    partial class InitialWithIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMSInteraction.Domain.Answer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<long>("SmsInteractionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SmsInteractionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("SMSInteraction.Domain.Lottery", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("SmsInteractionId")
                        .HasColumnType("bigint");

                    b.Property<int>("WinnerCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SmsInteractionId")
                        .IsUnique();

                    b.ToTable("Lottaries");
                });

            modelBuilder.Entity("SMSInteraction.Domain.SmsInteraction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationUtcDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DisabledUtcDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EnabledUtcDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InteractionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<long?>("LotteryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("SmsInteractions");

                    b.HasDiscriminator<int>("InteractionType").IsComplete(false);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SMSInteraction.Domain.UserAnswer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AnswerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationUtcDatetime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LotteryId")
                        .HasColumnType("bigint");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("SmsInteractionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("LotteryId");

                    b.HasIndex("SmsInteractionId");

                    b.HasIndex("MobileNo", "SmsInteractionId")
                        .IsUnique();

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("SMSInteraction.Domain.Contest", b =>
                {
                    b.HasBaseType("SMSInteraction.Domain.SmsInteraction");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("SMSInteraction.Domain.Survey", b =>
                {
                    b.HasBaseType("SMSInteraction.Domain.SmsInteraction");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("SMSInteraction.Domain.Answer", b =>
                {
                    b.HasOne("SMSInteraction.Domain.SmsInteraction", "SmsInteraction")
                        .WithMany("Answers")
                        .HasForeignKey("SmsInteractionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SmsInteraction");
                });

            modelBuilder.Entity("SMSInteraction.Domain.Lottery", b =>
                {
                    b.HasOne("SMSInteraction.Domain.SmsInteraction", "SmsInteraction")
                        .WithOne("Lottery")
                        .HasForeignKey("SMSInteraction.Domain.Lottery", "SmsInteractionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SmsInteraction");
                });

            modelBuilder.Entity("SMSInteraction.Domain.UserAnswer", b =>
                {
                    b.HasOne("SMSInteraction.Domain.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SMSInteraction.Domain.Lottery", "Lottery")
                        .WithMany("Winners")
                        .HasForeignKey("LotteryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SMSInteraction.Domain.SmsInteraction", "SmsInteraction")
                        .WithMany("UserAnswers")
                        .HasForeignKey("SmsInteractionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Lottery");

                    b.Navigation("SmsInteraction");
                });

            modelBuilder.Entity("SMSInteraction.Domain.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("SMSInteraction.Domain.Lottery", b =>
                {
                    b.Navigation("Winners");
                });

            modelBuilder.Entity("SMSInteraction.Domain.SmsInteraction", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Lottery");

                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
